version: "3"

services:
  codegen-api:
    image: amitthk/open-code-gen-api:0.1.1
    ports:
      - 0.0.0.0:8000:8000

  codegen-ui:
    image: amitthk/open-code-gen-ui:0.1.1
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8000
    ports:
      - 0.0.0.0:3000:3000
